apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cxflow.fullname" . }}
  labels:
    {{- include "cxflow.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cxflow.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cxflow.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "cxflow.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8585
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: CHECKMARX_BASE_URL
              value: {{ .Values.cxflow.checkmarxBaseUrl }}
            - name: CHECKMARX_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: checkmarx-password
            - name: CHECKMARX_TEAM
              value: {{ .Values.cxflow.checkmarxTeam }}
            - name: CHECKMARX_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: checkmarx-username
            - name: CX_FLOW_BUG_TRACKER
              value: {{ .Values.cxflow.bugTracker | upper }}
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: github-token
            - name: GITHUB_WEBHOOK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: github-webhook-token
            - name: MULTI_TENANT
              value: "true"
            - name: CHECKMARX_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: checkmarx-client-secret
            - name: JIRA_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: jira-token
            - name: JIRA_URL
              value: {{ .Values.cxflow.jiraUrl }}
            - name: JIRA_USERNAME
              value: {{ .Values.cxflow.jiraUserName }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
