apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-external-secret
spec:
  backendType: secretsManager
  dataFrom:
    - checkmarx/credentials
    - cxflow/sca
    - cxflow/ast
