apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
stringData:
  checkmarx-username: {{ .Values.cxflow.checkmarxUsername | quote }}
  checkmarx-password: {{ .Values.cxflow.checkmarxPassword | quote }}
  github-token: {{ .Values.cxflow.githubToken | quote }}
  github-webhook-token: {{ .Values.cxflow.githubWebhookToken | quote }}
  checkmarx-client-secret: {{ .Values.cxflow.checkmarxClientSecret | quote }}
  jira-token: {{ .Values.cxflow.jiraToken | quote }}
  
