name: Natalies Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - develop
      - pr-natalie-releasedraft1

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: natalieb07/release-drafter@v5.12.1.5
        with:
          # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
          config-name: release-drafter.yml
          prerelease: false
          publish: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
